version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.16-node-browsers
      # - image: cimg/php:7.4.14-browsers
    environment:
      - DB_CONNECTION: circleci
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: 'Create database and run migration'
          command: |
            touch storage/testing.sqlite
            php artisan migrate --env=testing --database=sqlite_testing --force
      - run:
          name: php test
          command: vendor/bin/phpunit
