version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.16-node-browsers
    environment:
      - DB_CONNECTION: circleci
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      # - run: npm ci
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run dev
      - run:
          name: 'Create database and run migration'
          command: |
            touch storage/testing.sqlite
            php artisan migrate --env=testing --database=sqlite_testing --force --seed
      - run:
          name: php test
          command: ./vendor/bin/phpunit
  #デプロイ
  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh  -o StrictHostKeyChecking=no -t ${USER_NAME}@${HOST_NAME} "cd /var/www/html/PF1 && \
              git pull"

              # git stash save && \
              # git stash pop && \

              # composer install -n --no-dev --prefer-dist && \
              # npm ci && \
              # npm run prod && \
              # php artisan config:cache"
              
              # ssh -i "kftrzeal.pem" ec2-user@54.238.195.5
              # cd /var/www/html/PF1
              # ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
              # run: ssh ${USER_NAME}@${HOST_NAME} 'cd [あなたのプロジェクトへのパス] && git pull'
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
