version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@4.1.1 # Windows Orb には Windows Executor の使用に必要なすべてが揃っています

jobs:
  build: # name of your job
    executor: win/default # executor type
    steps:
      - checkout
      # - run: sudo composer self-update --1
      # - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit tests/Feature/
