version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.16-node-browsers
      - image: cimg/mysql:8.0
    # environment:
    #   - DB_CONNECTION: circleci
    steps:
      - checkout
      # - run: sudo composer self-update --1
      # - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run: composer install
      # - run: touch database/database.mysql
      - run: php artisan migrate --env=testing
      - run:
          name: php test
          command: vendor/bin/phpunit
