version: 2.1

jobs:
  build: # name of your job
    machine:
      image: windows-default
    steps:
      - checkout
      # - run: sudo composer self-update --1
      # - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit tests/Feature/
