version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.16-node-browsers
      # - image: cimg/mysql:8.0
      # - image: circleci/mysql:8.0.20-ram
      #   command: mysqld --default-authentication-plugin=mysql_native_password
      #   environment:
      #     MYSQL_USER: forge
      #     MYSQL_DATABASE: forge
      #     MYSQL_ROOT_PASSWORD: ''
      #     MYSQL_PASSWORD: 'forge'
    # environment:
    #   - DB_CONNECTION: circleci
    steps:
      - checkout
      # - run: sudo composer self-update --1
      # - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: Install MySQL driver
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install zip bcmath pdo_mysql
      - run: composer install
      # - run: touch database/
      # - run: php artisan migrate --env=testing
      # - run: php artisan migrate --env=testing --database=circleci
      - run: php artisan migrate --env=testing --database=circleci --force
      - run:
          name: php test
          command: vendor/bin/phpunit
