version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
  steps:
    # Commands are run in a Windows virtual machine environment
    - checkout
    - run: npm ci
    - run: npm run dev
    - run:
      name: php test
      command: vendor/bin/phpunit
